/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HbiorTlORsa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Prata } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"
import 'framer-motion'

export function CV() {
  return (
    <div className="bg-background text-foreground p-4 sm:p-6 md:p-8 lg:p-12 rounded-lg shadow-lg max-w-3xl mx-auto">
      <header className="flex flex-col items-center mb-8 sm:flex-row sm:justify-between">
        <div className="flex flex-col items-center sm:items-start mb-4 sm:mb-0">
          <h1 className="text-2xl sm:text-3xl font-bold mb-2">Daniel M.</h1>
          <div className="flex flex-col sm:flex-row items-center sm:space-x-4 text-muted-foreground">
            <div className="flex items-center space-x-2 mb-2 sm:mb-0">
              <MailIcon className="w-4 h-4 sm:w-5 sm:h-5" />
              <span className="text-sm sm:text-base">daniel.mrn@gmail.com</span>
              
            </div>
            <div className="flex items-center space-x-2 mb-2 sm:mb-0">
              <PhoneIcon className="w-4 h-4 sm:w-5 sm:h-5" />
              <span className="text-sm sm:text-base">07 68 09 11 **</span>
            </div>
            <div className="flex items-center space-x-2">
              <LocateIcon className="w-4 h-4 sm:w-5 sm:h-5" />
              <span className="text-sm sm:text-base">Lons-Le-Saunier</span>
            </div>
          </div>
        </div>
        <Image
          src="/mi.jpg"
          width={128}
          height={128}
          alt="John Doe"
          className="rounded-full mt-4 md:mt-0"
          style={{ aspectRatio: "128/128", objectFit: "cover" }}
          quality={100}
        />
      </header>
      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">A propos de moi</h2>
        <div className="flex items-center space-x-2 mb-2">
          <span>👋</span>
          <span>salut, je suis Daniel M.</span>
        </div>
        <p className="text-muted-foreground">
          Je suis un ingénieur logiciel passionné et expérimenté avec une solide expérience en développement web full-stack. J&apos;ai
          fait mes preuves dans la livraison d&apos;applications de haute qualité, évolutives et conviviales. Je suis toujours
          désireux d&apos;apprendre de nouvelles technologies et de rester à jour avec les dernières tendances de l&apos;industrie.
        </p>
      </section>
      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Expérience professionnelle</h2>
        <div className="space-y-6">
          <div>
            <div className="flex items-center space-x-2 mb-2">
              <BriefcaseIcon className="w-6 h-6" />
              <h3 className="font-bold">Développeur Full-Stack</h3>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <CalendarIcon className="w-5 h-5" />
              <span>2023 - 2024</span>
            </div>
            <p className="text-muted-foreground">
              Développement et maintenance d&apos;applications web complexes utilisant React, Node.js et MongoDB. Collaboration avec
              équipes interfonctionnelles pour livrer des fonctionnalités de haute qualité et des améliorations.
            </p>
          </div>
          <div>
            <div className="flex items-center space-x-2 mb-2">
              <BriefcaseIcon className="w-6 h-6" />
              <h3 className="font-bold">Développeur Full-Stack</h3>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <CalendarIcon className="w-5 h-5" />
              <span>2018 - 2019</span>
            </div>
            <p className="text-muted-foreground">
              Expérience pratique dans le développement web, y compris la création de pages web responsives, l&apos;intégration d&apos;APIs et la participation à des processus de développement agile.
            </p>
          </div>
        </div>
      </section>
      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Skills</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          <div className="flex items-center space-x-2">
            <LaptopIcon className="w-6 h-6" />
            <span>React.js</span>
          </div>
          <div className="flex items-center space-x-2">
            <ServerIcon className="w-6 h-6" />
            <span>Node.js</span>
          </div>
          <div className="flex items-center space-x-2">
            <DatabaseIcon className="w-6 h-6" />
            <span>MongoDB</span>
          </div>
          <div className="flex items-center space-x-2">
            <CodepenIcon className="w-6 h-6" />
            <span>CSS3</span>
          </div>
          <div className="flex items-center space-x-2">
            <Heading5Icon className="w-6 h-6" />
            <span>HTML5</span>
          </div>
          <div className="flex items-center space-x-2">
            <GitGraphIcon className="w-6 h-6" />
            <span>Git</span>
          </div>
        </div>
      </section>
      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Formation</h2>
        <div className="space-y-6">
          <div>
            <div className="flex items-center space-x-2 mb-2">
              <GraduationCapIcon className="w-6 h-6" />
              <h3 className="font-bold">Certification Python expert tosa</h3>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <CalendarIcon className="w-5 h-5" />
              <span>2024</span>
            </div>
            <p className="text-muted-foreground">
              Titre RNCP de Niveau II
            </p>
          </div>
          <div>
            <div className="flex items-center space-x-2 mb-2">
              <GraduationCapIcon className="w-6 h-6" />
              <h3 className="font-bold">BTS Techniques de commercialisation</h3>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <CalendarIcon className="w-5 h-5" />
              <span>2020 - 2022</span>
            </div>
            <p className="text-muted-foreground">Brevet de technicien supérieur</p>
          </div>
          <div>
            <div className="flex items-center space-x-2 mb-2">
              <GraduationCapIcon className="w-6 h-6" />
              <h3 className="font-bold">Baccalauréat</h3>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <CalendarIcon className="w-5 h-5" />
              <span>2018 - 2020</span>
            </div>
            <p className="text-muted-foreground">Baccalauréat</p>
          </div>
        </div>
      </section>
      <footer className="flex justify-center space-x-4 mt-8">
        <Link href="https://www.linkedin.com/in/daniel-081659285/" className="text-muted-foreground hover:text-foreground" prefetch={false} target="_blank" rel="noopener noreferrer">
          <LinkedinIcon className="w-6 h-6" />
        </Link>
        <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false} target="_blank" rel="noopener noreferrer">
          <GithubIcon className="w-6 h-6" />
        </Link>
        <Link href="https://x.com/DNservices_" className="text-muted-foreground hover:text-foreground" prefetch={false} target="_blank" rel="noopener noreferrer">
          <TwitterIcon className="w-6 h-6" />
        </Link>
      </footer>
    </div>
  )
}

function BriefcaseIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function CalendarIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function CodepenIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function DatabaseIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function GitGraphIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}


function GithubIcon(props: React.SVGProps<SVGSVGElement>  ) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function GraduationCapIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
      <path d="M22 10v6" />
      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
    </svg>
  )
}


function HandIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 11V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0" />
      <path d="M14 10V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v2" />
      <path d="M10 10.5V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v8" />
      <path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
    </svg>
  )
}


function Heading5Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12h8" />
      <path d="M4 18V6" />
      <path d="M12 18V6" />
      <path d="M17 13v-3h4" />
      <path d="M17 17.7c.4.2.8.3 1.3.3 1.5 0 2.7-1.1 2.7-2.5S19.8 13 18.3 13H17" />
    </svg>
  )
}


function LaptopIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function LinkedinIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function LocateIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}


function MailIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function PhoneIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function ServerIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="8" x="2" y="2" rx="2" ry="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" ry="2" />
      <line x1="6" x2="6.01" y1="6" y2="6" />
      <line x1="6" x2="6.01" y1="18" y2="18" />
    </svg>
  )
}


function TwitterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
